<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class HarvestTelemetry extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'harvest:telemetry';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'This command will scour the files generated by something.sh to get hardware data  
        and create database entries based on that data. There will also need to be some sort of user engagement but 
         that may need to be another job entirely. This will be used to power most of the dashboard charts.
        
        For now it creates fake entries to populate the usage_counts table with things to display
        on the dashboard to help format it. TODO is to switch over to real data';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(){
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(){



        return 0;
    }
}
